name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@master
      with: 
        python-version: '3.7'
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Upgrade pip
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install Dependancies
      run: sudo apt-get install make gcc bison git -y
    - name: Install Pillow
      run: pip install pillow
    - name: Make (Build)
      run: make
